### ISSUE TITLE
Running quickstart doesnt work

### ISSUE THREAD

**Issue by edeandrea** [wildfly/wildfly-operator#156]
I'm trying to run the quickstart on an OpenShift 4.5 cluster after installing the operator from the marketplace but it doesn't seem to work. When trying to run the application pod I'm getting

`Readiness probe failed: /bin/bash: /opt/eap/bin/readinessProbe.sh: No such file or directory`

`Liveness probe failed: /bin/bash: /opt/eap/bin/livenessProbe.sh: No such file or directory`

I get the exact same error when trying to run the clustered example.

**Comment by jmesnil** [comment]
These errors correspond to the EAP Operator, not the upstream WildFly Operator.
This likely mean that you have used the EAP Operator to deploy application image built with WildFly S2I.

Could you please confirm if that's the case?

**Comment by edeandrea** [comment]
Thanks @jmesnil yes that is the case. I couldn't find any quickstarts for the eap operator.
