### ISSUE TITLE
The operator doesn't build

### ISSUE THREAD

**Issue by jfclere** [wildfly/wildfly-operator#158]
+++
[jfclere@pc-72 wildfly-operator]$ make build
go mod tidy
go: github.com/operator-framework/operator-sdk@v0.17.2 requires
	k8s.io/kubectl@v0.17.4 requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": reading https://vbom.ml/util?go-get=1: 503 Service Unavailable
make: *** [Makefile:22: tidy] Error 1
+++
I guess something has been deprecated...

**Comment by jfclere** [comment]
[jfclere@pc-72 jws-image-operator]$ curl https://vbom.ml/util?go-get=1
Go 1.9 is no longer available.  Please refer to https://goo.gl/aESk5L for more information.[jfclere@pc-72 jws-image-operator]$

**Comment by jmesnil** [comment]
Have you tried upgrading your Go version?

the `go.mod` file requires Go 1.13.

**Comment by jfclere** [comment]
[jfclere@pc-7 demo-webapp]$ go version
go version go1.14.6 linux/amd64

**Comment by jfclere** [comment]
The problem is gone now... Weird.
Could it be the version of the operator-framework/operator-sdk?
I have down upgraded it to v0.17.x
[jfclere@pc-7 operator-sdk]$ git remote -v
origin	https://github.com/operator-framework/operator-sdk (fetch)
origin	https://github.com/operator-framework/operator-sdk (push)
[jfclere@pc-7 operator-sdk]$ git branch
  master
* v0.17.x
+++
I had master when reporting the issue...

**Comment by jmesnil** [comment]
closing as out of date
