### ISSUE TITLE
TestWildFly18Server/ClusterTest is failing in CI after recent OpenShift and image upgrade

### ISSUE THREAD

**Issue by simkam** [wildfly/wildfly-operator#171]
Recently we [updated](https://github.com/openshift/release/pull/15041) OpenShift to 4.6 (from 4.3) and used base image from `ubi-minimal:7` to `ubi-minimal:8`.

There was one failure in `rehearse` job (job does the same as PR check but with master branch), the failed test is `TestWildFly18Server/ClusterTest`. 

It looks like it is failing with error [(full log)](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15041/rehearse-15041-pull-ci-wildfly-wildfly-operator-master-test-e2e-prow/1351541011855183872)
```
15:42:55,292 WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (thread-6,null,h-1611070656368095261-1) failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:1008#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@66cec0e4] for cluster [ejb], namespace [osdk-e2e-306a618f-779c-49a6-aad6-31b2f4137d88], labels [app.kubernetes.io/managed-by=wildfly-operator,app.kubernetes.io/name=clusterbench-1611070656368095261,app.openshift.io/runtime=wildfly]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
```
Although message is marked as `WARN`, the test eventually times out. 

The error might indicate issue with used JDK, cause might be upgrade of base image. 

(After upgrade we had only single CI run so it might be only intermittent)

**Comment by mchoma** [comment]
`SSLHandshakeException: extension (5) should not be presented in certificate_request`

Really seemed to be jdk issue.  https://bugs.openjdk.java.net/browse/JDK-8236039

**Comment by jmesnil** [comment]
The base image of the WildFly operator should not be related to this: it is used to run the operator (which is a Golang application).
The JDK issue is on the *application image* that runs the WildFly application.

Maybe we should update the application image that is used by the test `quay.io/wildfly-quickstarts/clusterbench-ee7`

**Comment by jmesnil** [comment]
fixed in https://github.com/wildfly/wildfly-operator/pull/172
