### ISSUE TITLE
Expose WildFly Metrics to Prometheus by creating a ServiceMonitor

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-operator#25]
# Expose WildFly Metrics to Prometheus by creating a ServiceMonitor

## Issue Metadata

* https://github.com/wildfly/wildfly-operator/issues/25

## Related Issues

* [EAP7-1579 - As a developer, I want to monitor metrics from application deployed with the EAP Operator](https://issues.redhat.com/browse/EAP7-1579)

### Dev Contacts

* https://github.com/jmesnil

### QE Contacts

* [Jan Kasik](mailto:jkasik@redhat.com)

### Testing By

* [x] QE

### Affected Projects or Components

* [WildFly Operator](https://github.com/wildfly/wildfly-operator)

## Requirements

* Expose WildFly Metrics (from the `/metrics` HTTP endpoint on its management port) so that they can be monitored out-of-the-box by the OpenShift Monitoring tools (based on Prometheus). This is achieved by creating a `ServiceMonitor` resource (owned by the Prometheus Operator) that tells Prometheus servers that they can query metrics from WildFly on its management port.

### Non-Requirements

* The installation of the Prometheus operator (that provides the `ServiceMonitor`) is out of scope. If the WildFly Operator does not detect the presence on the `ServiceMonitor` CRD, it will do nothing.

### Implementation Plan

When the WildFly Operator watches a `WildFlyServer` resource, it will checks for the presence of the `ServiceMonitor` CRD and eventually create a `ServiceMonitor` that expose its metrics.
In any case the WildFly Operator also creates a `Service` to expose its admin/management port to the cluster.

## Community Documentation

This RFE does not impact the `WildFlyServer` CRD.
The community documentation will only mention that if the Prometheus Operator is deployed on the cluster (and the `ServiceMonitor` CRD is installed), then WildFly metric can be consumed out-of-the-box.

## Release Note Content

> Application deployed by the WildFly Operator  provides metrics that can be monitored out-of-the-box. It requires the installation of the Prometheus Operator.

**Comment by jmesnil** [comment]
code snippet provided by @simonpasquier: https://gist.github.com/simonpasquier/275152a57423867b07e6995b3a73af34

**Comment by mchoma** [comment]
What if I am not interested in metrics exposed to Prometheus. Can I turn off this behaviour? What overhead does this brings? On our cluster OCP4.6 there is ServiceMonitor CRD by default. I am not aware we installed that explicitely.

**Comment by jmesnil** [comment]
This behaviour can not be turned off. Having a way to observe metrics from an application is a key feature and I don't see why we would turn that off.

The overhead is a regular call from Prometheus to the `/metrics` HTTP endpoint to gather metrics.

**Comment by mchoma** [comment]
So do I understand correctly idea is just `ServiceMonitor` CR is created by EAP Operator. `Prometheus` CR will not be created by EAP Operator.

[1] https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

**Comment by jmesnil** [comment]
that's correct, all this PR does is advertise to Prometheus (using a `ServiceMonitor`) that WildFly exposes metrics.

**Comment by honza-kasik** [comment]
@jmesnil The standard OCP installation includes OpenShift monitoring stack which includes Prometheus. Does this mean that ServiceMonitor CR will be always created in this situation when ServiceMonitor CRD is present?

**Comment by jmesnil** [comment]
that's correct, if the WildFly operator detects that the ServiceMonitor CRD is installed (whether from the Prometheus operator or from the OCP monitoring stack), it will create a `ServiceMonitor` resource.

**Comment by honza-kasik** [comment]
@jmesnil Thanks, this analysis document looks good from QA point of view apart from missing QE contact.
