### ISSUE TITLE
createLivenessProbe() and createReadinessProbe() actually reads opeartor container env 

### ISSUE THREAD

**Issue by jimma** [wildfly/wildfly-operator#51]
If I understand correctly, createReadinessProbe() and createReadinessProbe() reads the operator container Env:
https://github.com/wildfly/wildfly-operator/blob/master/pkg/controller/wildflyserver/wildflyserver_controller.go#L529
https://github.com/wildfly/wildfly-operator/blob/master/pkg/controller/wildflyserver/wildflyserver_controller.go#L557
Should this be configured and read from env from WildflyServerSpec ?

**Comment by jmesnil** [comment]
No, this is not meant to be something configured by the user in theWildFlyServerSpec. 
This is considered an implementation detail internal to the operator.

The reason for these 2 env vars is that EAP has existing CLI scripts that are used as liveness/readiness probes (they are available in the [os-eap-probes modules](https://github.com/jboss-container-images/jboss-eap-modules/tree/master/os-eap-probes/2.0).

The WildFly operator will use the HTTP `/health` endpoint for its liveness (and has no readiness probes).
But the EAP operator will uses these 2 env vars to use its own scripts probes instead by specifying their paths in its own `Dockerfile`.

Does that make sense?

**Comment by jimma** [comment]
This function is executed in wildfly-opeartor container:
`func createLivenessProbe(w *wildflyv1alpha1.WildFlyServer) *corev1.Probe `
 
Does this line only read the wildfly-operator container env before the eap container starts , and the env configured in `DockerFile` for WFLY/EAP image doesn't take effect ?
`readinessProbeScript, defined := os.LookupEnv("SERVER_READINESS_SCRIPT")
`

**Comment by jmesnil** [comment]
The operator code is executed inside the *operator image*.
It reads the env from the *operator image*, not from the *application image*.

It does not have access to any env vars from the application image (whether they are set in its Dockerfile or in the WildFlyServerSpec).

**Comment by jimma** [comment]
So env var  SERVER_READINESS_SCRIPT/SERVER_LIVENESS_SCRIPT are configured through https://github.com/wildfly/wildfly-operator/blob/master/deploy/operator.yaml or  operator image, right ?

**Comment by jmesnil** [comment]
Right. for the EAP operator, I'll likely put the envs in its `Dockerfile` (using Cekit module) so that the operator.yaml does not have to change between WildFly and EAP.

**Comment by jimma** [comment]
I am thinking if the configuration items for liveness and readiness should belong to WildflyServer crds. 
Then user can define the  exec probe or httpget probe for ApplicationImage defined in WildflyServer Spec. 
Now, I can't figure out how the httpGet probe for http://host:9090/health/live or http://host:9090/health/ready can be configured if user defined liveness and readiness health check with microprofile-health api.

**Comment by jmesnil** [comment]
>Now, I can't figure out how the httpGet probe for http://host:9090/health/live or http://host:9090/health/ready can be configured if user defined liveness and readiness health check with microprofile-health api. 

These HTTP endpoints will aggregates results from the user-defined health probes that are deployed in the user application.

readiness and liveness probes are specific to the application server.
The only reason they are customisable is that WildFly only provide support for the MP health HTTP endpoints while EAP provides scripts with additional health checks.

An user that deploys its application with the operator should not be concerned with how the app server reports its healthiness/liveness to the container platform.

**Comment by jimma** [comment]
> readiness and liveness probes are specific to the application server.
> The only reason they are customisable is that WildFly only provide support for the MP health HTTP endpoints while EAP provides scripts with additional health checks.

Do you mean the EAP could not have the MP health support, so it has to use [these scripts](https://github.com/jboss-container-images/jboss-eap-modules/tree/master/os-eap-probes/2.0/) to 
do health check ?

> An user that deploys its application with the operator should not be concerned with how the app server reports its healthiness/liveness to the container platform.

I don't know too much MP health check, but from api and doc, its purpose to support this kind of usage, right ?  IMHO, if there user defined liveness and healthiness probes with MP health check api, operator should configure it for pod/container instead of the scripts. Moreover, these http endpoints are very simple and fast for k8s to check.

**Comment by jmesnil** [comment]
As I wrote, EAP uses scripts for the liveness / readiness probe. These probes has many checks *including the MP health endpoints*.

If an EAP user has defined MP Health Checks procedures, they are taken into account by the EAP readiness/liveness probes

**Comment by jimma** [comment]
Thanks for more details. That's all I want to know. Close this issue now.

**Comment by mnovak1** [comment]
@jmesnil @jimma hi guys, sorry for re-opening this discussion.

I agree that operator should provide some reasonable defaults for probes.

But based on discussion above it won't be possible to define liveness/readiness probe differently from default. And in case when there are more deployed applications, it won't be possible to define different configuration of probes for each of them.

EAP probes can be defined in the running pod like:
```
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - '-c'
            - /opt/eap/bin/livenessProbe.sh
        initialDelaySeconds: 60
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
```
I think there should possible to configure all probes attributes in WildflyServerSpec.

**Comment by jmesnil** [comment]
@mnovak1 Probes are an implementation detail for the operator and the user should not have to configure them.

Internally the operator can either use HTTP call to WildFly OR specify the execution of a script.
When the WildFly Operator is productize for EAP, we will use the `/opt/eap/bin/livenessProbe.sh` to check the liveness of EAP: https://github.com/jbossas/eap-operator-packaging/blob/fa451d6443657be18a80b1528f3c3302e31646ef/release-operator/cekit/image.yaml#L22-L25

> And in case when there are more deployed applications, it won't be possible to define different configuration of probes for each of them

I don't understand your point. Please note that for EAP CD we only support one deployed application per server (and we should recommend the same for WildFly)

**Comment by mnovak1** [comment]
@jmesnil thanks Jeff. Yes, there will be one application per server (WildflyServer). What I tried to say there can be more applications (more WildflyServer definitions) and each will need different configuration of probes.

Currently for EAP CD the probe will look like:
```      
livenessProbe:
        exec:
          command:
            - /bin/bash
            - '-c'
            - /opt/eap/bin/livenessProbe.sh
```

by default but what if customer/user needs to change something, for example after how many failures of probe container will be restarted or how often the probe should be triggered. For example customer/user needs configuration of probe look like:
```
livenessProbe:
        exec:
          command:
            - /bin/bash
            - '-c'
            - /opt/eap/bin/livenessProbe.sh
        initialDelaySeconds: 60
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
```
It won't be possible to do so using operator atm.

**Comment by pkremens** [comment]
@jmesnil I believe @mnovak1 is referring to https://docs.okd.io/latest/dev_guide/application_health.html which were user able to change while using the DeploymentConfig with other configuration options like resource limits, pod autoscaling, etc. which are now not available.
