### ISSUE TITLE
Do not restart server to configure recovery properties

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-operator#77]
`setupRecoveryPropertiesAndRestart` should be removed.

Server should be configured properly with these system properties when it is configured with tx recovery enabled.
But the operator should not attempt to restart the server to setup those.

**Comment by jmesnil** [comment]
@ochaloup  could you please take this issue?

**Comment by ochaloup** [comment]
@jmesnil sure, I will

**Comment by ochaloup** [comment]
The recovery has to be configured to define the backoff period and orphan detection period to be the lowest possible values. If it's left for defaults then the finishing of in-doubt transactions may take few minutes instead of ten seconds.

**Comment by ochaloup** [comment]
@jmesnil pert discussion on the IM I consider this to be closed as "Won't fixed".

The reason for having the app server restart is to speed-up recovery processing during scale down.

**Comment by jmesnil** [comment]
I agree, there is nothing more that can be done on the operator side. I'm closing this issue.

However there is still room for improvements on the Narayana side. Eg. the recovery process could take into account the sys prop at runtime (instead of reading it once when the TM is started) or the transactions subsystem could provide a management operator for tx recovery that would take these settings as parameters of the operation.
